### ISSUE TITLE
Network Not Connected on Dashboard

### ISSUE THREAD

**Issue by chanwoner** [officialputuid/xGrassBot#1]
log show success,but dashborad no network connect

**Comment by Bekloppten** [comment]
i have the same problem with every bot the since a few days. tried new accounts, everything. no bot seems to be working at the moment
please tell me, if u find a solution

**Comment by Solana0x** [comment]
Hi code is not working

**Comment by officialputuid** [comment]
![image](https://github.com/user-attachments/assets/fe979b4b-c489-4a13-ac3c-22f52f2b9d83)

Fine here.

**Comment by chanwoner** [comment]
![image](https://github.com/user-attachments/assets/ff8a42ba-588c-43df-b9b9-32332b4e284b)
it run for 30 min, but it still does not display 'connect'

**Comment by Solana0x** [comment]
can you send me your Discord ? its really isnt working i tried with a new grass account too

**Comment by GabSanPro** [comment]
> ![image](https://private-user-images.githubusercontent.com/38780082/395835488-ff8a42ba-588c-43df-b9b9-32332b4e284b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzA0MjYsIm5iZiI6MTczNDI3MDEyNiwicGF0aCI6Ii8zODc4MDA4Mi8zOTU4MzU0ODgtZmY4YTQyYmEtNTg4Yy00M2RmLWI5YjktMzIzMzJiNGUyODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDEzNDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNzEzZmNhYjBjZTUwN2ZlMTY3MDk3OTA1NGY3NTc5ZmY5ZDRiZDRiNjUzMGMwMDIwOGNhNTJhYjIwZTVlZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mxAOsd_QX0JYhNZE-NerMH2OKDHyhShqkU4xWGheQRU) it run for 30 min, but it still does not display 'connect'

Hi, mine is working with socks but not with http, that http proxy isp good quality im using in nodepay gradient and works fine.. maybe some update to something i need to make? the error is forbiden 403

**Comment by alexnovikovvvv** [comment]
> ![image](https://private-user-images.githubusercontent.com/38780082/395835488-ff8a42ba-588c-43df-b9b9-32332b4e284b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzcyODAsIm5iZiI6MTczNDYzNjk4MCwicGF0aCI6Ii8zODc4MDA4Mi8zOTU4MzU0ODgtZmY4YTQyYmEtNTg4Yy00M2RmLWI5YjktMzIzMzJiNGUyODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE5MzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NTc3NDQ3NzhkMWRjODFlMTZmMGI5ZTczMzY3NDJlOGU4ZDNlZDZjOTE3MDU2ZjI2MjA0M2ZhNThiNjBhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DFCTICyExmgR78_ss4BcQqgzzCdTNZy1dKZZ0k8u3bU) it run for 30 min, but it still does not display 'connect'

the same! Thank a lot for script

**Comment by CrateC** [comment]
![Screenshot from 2024-12-20 07-26-10](https://github.com/user-attachments/assets/e45df85a-4197-44be-bedb-b6d0386b86e9)

**Comment by lumanyy** [comment]
运行不会报错 但是不会连接

**Comment by cthujh2** [comment]
code is not working

**Comment by alexnovikovvvv** [comment]
anyone tried work with extension type?
